# Generated by Django 4.2.4 on 2024-10-01 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Icebreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2024, 10, 1, 20, 4, 15, 804740, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата проводки')),
                ('start_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Начальная точка проводки')),
                ('finish_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Конечная точка проводки')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'db_table': 'icebreakers',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('ice_class', models.CharField(blank=True, max_length=10, verbose_name='Ледовый класс')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Длина')),
                ('engine', models.CharField(blank=True, max_length=255, verbose_name='Двигатель')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(default='images/default.png', upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Корабль',
                'verbose_name_plural': 'Корабли',
                'db_table': 'ships',
            },
        ),
        migrations.CreateModel(
            name='ShipIcebreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=50, null=True, verbose_name='Порядок')),
                ('icebreaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.icebreaker', verbose_name='Проводка')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.ship', verbose_name='Корабль')),
            ],
            options={
                'verbose_name': 'Связь корабль-проводка',
                'verbose_name_plural': 'Связи корабль-проводка',
                'db_table': 'ship_icebreaker',
            },
        ),
    ]
