# Generated by Django 4.2.4 on 2024-10-01 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 20, 15, 40, 718446, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
