# Generated by Django 4.2.4 on 2024-10-08 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_icebreaker_date_created_alter_ship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 13, 8, 17, 795298, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
