# Generated by Django 4.2.4 on 2024-10-13 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0007_alter_icebreaker_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='title',
            new_name='ship_name',
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 16, 39, 29, 452556, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
