# Generated by Django 4.2.4 on 2024-10-13 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0008_rename_title_ship_ship_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 16, 55, 21, 632243, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
