# Generated by Django 4.2.4 on 2024-10-13 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0009_alter_icebreaker_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 17, 31, 7, 334616, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
