# Generated by Django 4.2.4 on 2024-10-13 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0015_alter_icebreaker_date_created_alter_ship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 13, 20, 32, 44, 45723, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.CharField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
