# Generated by Django 4.2.4 on 2024-10-19 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0018_alter_icebreaker_date_created_alter_ship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 22, 30, 44, 765542, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.ImageField(default='image/default.png', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
