# Generated by Django 4.2.4 on 2024-11-04 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0019_icebreaker_result_alter_icebreaker_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 12, 4, 40, 670437, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
