# Generated by Django 4.2.4 on 2024-11-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0020_alter_icebreaker_date_created_alter_ship_image'),
        ('bmstu_lab', '0021_alter_icebreaker_date_created_and_more'),
    ]

    operations = [
    ]
