# Generated by Django 4.2.4 on 2024-11-18 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0022_merge_20241104_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 19, 13, 22, 485289, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='image',
            field=models.CharField(blank=True, default='images/default.png', null=True, verbose_name='Изображение'),
        ),
    ]
