# Generated by Django 4.2.4 on 2024-11-18 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0023_alter_icebreaker_date_created_alter_ship_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 19, 34, 13, 309990, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
