# Generated by Django 4.2.4 on 2024-11-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0024_alter_icebreaker_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 12, 27, 40, 211063, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='result',
            field=models.BooleanField(default=False, null=True, verbose_name='Результат проводки (0/1)'),
        ),
    ]
