# Generated by Django 4.2.4 on 2024-11-30 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0025_alter_icebreaker_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 22, 59, 47, 593193, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
