# Generated by Django 4.2.4 on 2024-12-08 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0026_alter_icebreaker_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='status',
        ),
        migrations.AddField(
            model_name='ship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 0, 3, 44, 350425, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='icebreaker',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10),
        ),
    ]
